### ISSUE TITLE
Captcha Regression

### ISSUE THREAD

**Issue by div72** [hacettepeoyt/oyt-website#28]
The new captcha is a major regression compared to the older simpler version.

**Comment by furkansimsekli** [comment]
@div72
I'm going to use the same dumb captcha we used in the old website. However, because I used something called Layout to automate form rendering, I'm not able to quickly make such a change. First, I need to convert the current form to plain html.

I don't have enough free time due to internship. I can promise to resolve this issue with #16, #19, #21, #24 together in one sit in mid August. I can't tell how hard for me to sit and work on this when I don't have the motivation :) watching another game of thrones episode seems more fun hah
